export enum Card {
    ExplodingKitten = "exploding_kitten",
    Defuse = "defuse",
    Nope = "nope",
    Attack = "attack",
    Skip = "skip",
    Favor = "favor",
    Shuffle = "shuffle",
    SeeTheFuture = "see_the_future",
    TacoCat = "taco_cat",
    Catermelon = "catermelon",
    HairyPotatoCat = "hairy_potato_cat",
    RainbowRalphingCat = "rainbow_ralphing_cat",
    BeardCat = "beard_cat",
}